### ISSUE TITLE
Where to put template files?

### ISSUE THREAD

**Issue by qrhfz** [javalin/javalin-rendering#20]
i find conflicting explainations. in the [docs](https://javalin.io/plugins/rendering) it says

> All the template engines look for templates/markdown files in src/resources,

but the readme says

> By default, the plugin will look in src/main/resources/templates for template files.

**Comment by tipsy** [comment]
I'll find out and fix the documentation 😅

**Comment by tipsy** [comment]
"/templates" dir is correct. I've updated the docs, thank you !
