### ISSUE TITLE
Precompiled Jte tests use generated output from test sources

### ISSUE THREAD

**Issue by dzikoysk** [javalin/javalin-rendering#22]
The whole precompiled directory shouldn't be a part of test sources, e.g.:

https://github.com/javalin/javalin-rendering/blob/main/src/test/java/io/javalin/jte/precompiled/JtetestGenerated.java

These classes should be generated by Maven plugin:

https://github.com/casid/jte/blob/main/DOCUMENTATION.md#maven

**Comment by tipsy** [comment]
@casid thoughts on this? Could you update the integration to JTE3?

**Comment by casid** [comment]
I think we included the classes to speed up test execution. Generating them by the maven plugin would indeed be nicer (and probably unnoticed in build time).

@tipsy I haven't created a PR yet, since Javalin Rendering still supports Java 11 and jte 3 requires Java 17 as baseline.

**Comment by tipsy** [comment]
We are moving to Java 17 for 6x, and I am moving rendering to 6x as we speak :)

**Comment by tipsy** [comment]
Pushed repo to v6 now

**Comment by tipsy** [comment]
Rendering is in 6.x now.
