### ISSUE TITLE
jte-kotlin required in java projects

### ISSUE THREAD

**Issue by ishehadeh** [javalin/javalin-rendering#8]
Hi, I'm currently writing a Java web app with javalin + jte. Since I upgraded to version 5 of Javalin, I started using this package which requires `jte-kotlin` to be included in my dependencies in addition to `jte`. Is there any way around this? It isn't a big deal, but I'd rather keep the number of dependencies down if possible.

**Comment by tipsy** [comment]
This seems like a bug @ishehadeh, maybe something happened during the transfer.

**Comment by tipsy** [comment]
Found the offending line @ishehadeh, will fix.

**Comment by tipsy** [comment]
FIxed in https://github.com/javalin/javalin-rendering/commit/c5d15016dc44909428243a72ae0de6fe22e65db2 :)

**Comment by ishehadeh** [comment]
Wow that was fast! Thanks!
