### ISSUE TITLE
TemplateUtil.model(...) function is missing

### ISSUE THREAD

**Issue by RaniAgus** [javalin/javalin-rendering#9]
Old `model(...)` method used for rendering templates has been removed in d14e9d792681c5592072a8d5ea5f092b554657f7 but still appears in the docs https://javalin.io/documentation#views-and-templates, was it removed by accident?

Maybe in Kotlin is not so necessary because we can use `mapOf(...)`, but in Java it could be useful because `Map.of(...)` method doesn't accept nulls.

**Comment by tipsy** [comment]
> Maybe in Kotlin is not so necessary because we can use mapOf(...), but in Java it could be useful because Map.of(...) method doesn't accept nulls.

That's absurd, didn't know that!
